FROM rust:1.82-bookworm AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends mingw-w64 && rm -rf /var/lib/apt/lists/*
RUN rustup target add x86_64-pc-windows-gnu

COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src && echo "fn main() {}" > src/main.rs
RUN cargo build --release --target x86_64-pc-windows-gnu
RUN rm -rf src

COPY . .
RUN cargo build --release --target x86_64-pc-windows-gnu